# TextReplacer for Nukkit
# Simply change the texts or messages which is sent by the server or other plugins.
# Available variables: {PLAYER}, {LEVEL}
# Format: "Text to be replaced": "Text you want"

# Message on player joined.
"{PLAYER} joined the game.": "Welcome {PLAYER} to the server!"